import os
import asyncio
from unittest.mock import AsyncMock, MagicMock

from fastapi.testclient import TestClient

from app.core.config import get_settings
from app.main import app


def _headers():
    return {
        "X-Request-Id": "req-1",
        "X-Trace-Id": "trace-1",
        "X-Session-Id": "sess-1",
    }


def _payload():
    return {
        "model": "BAAI/bge-reranker-v2-m3",
        "query": "What is Paris?",
        "documents": [
            "Paris is the capital of France.",
            "Berlin is the capital of Germany.",
        ],
    }


def test_health():
    with TestClient(app) as client:
        response = client.get("/health")
    assert response.status_code == 200


def test_ready(monkeypatch):
    async def fake_probe(*_args, **_kwargs):
        return {"reranker-node-1": "healthy", "reranker-node-2": "healthy"}

    monkeypatch.setattr("app.main.probe_backends", fake_probe)
    with TestClient(app) as client:
        response = client.get("/ready")
    assert response.status_code == 200
    assert response.json()["status"] == "ready"
    assert response.json()["healthy_backends"] == 2


def _mock_upstream_ok(client: TestClient) -> None:
    mock_resp = MagicMock()
    mock_resp.status_code = 200
    mock_resp.content = b"{}"
    mock_resp.headers = {"content-type": "application/json"}
    client.app.state.gateway_context.client.post = AsyncMock(return_value=mock_resp)


def test_autogenerated_correlation_headers_when_omitted():
    get_settings.cache_clear()
    with TestClient(app) as client:
        _mock_upstream_ok(client)
        response = client.post("/v1/rerank", json=_payload())
        assert response.status_code == 200
        post = client.app.state.gateway_context.client.post
        assert post.await_count == 1
        sent = post.call_args.kwargs["headers"]
        for key in ("X-Request-Id", "X-Trace-Id", "X-Session-Id"):
            assert key in sent
            assert len(sent[key]) >= 32


def test_partial_correlation_headers_filled():
    get_settings.cache_clear()
    with TestClient(app) as client:
        _mock_upstream_ok(client)
        response = client.post(
            "/v1/rerank",
            headers={"X-Request-Id": "client-req-only"},
            json=_payload(),
        )
        assert response.status_code == 200
        sent = client.app.state.gateway_context.client.post.call_args.kwargs["headers"]
        assert sent["X-Request-Id"] == "client-req-only"
        assert sent["X-Trace-Id"]
        assert sent["X-Session-Id"]


def test_admission_queue_timeout_rejects_request():
    os.environ["ADMISSION_WAIT_TIMEOUT_MS"] = "1"
    get_settings.cache_clear()
    with TestClient(app) as client:
        client.app.state.gateway_context.queue = asyncio.Semaphore(0)
        response = client.post("/v1/rerank", headers=_headers(), json=_payload())
    assert response.status_code == 429


def test_invalid_payload_releases_admission_slot():
    """Regression: body parse/validation must not leak admission semaphore slots."""
    os.environ["ADMISSION_MAX_CONCURRENT"] = "1"
    get_settings.cache_clear()
    try:
        with TestClient(app, raise_server_exceptions=False) as client:
            _mock_upstream_ok(client)
            bad = client.post("/v1/rerank", json={"model": "m"})
            assert bad.status_code >= 400
            good = client.post("/v1/rerank", json=_payload())
            assert good.status_code == 200
    finally:
        os.environ.pop("ADMISSION_MAX_CONCURRENT", None)
        get_settings.cache_clear()


def test_correlation_ids_in_body_returns_400():
    get_settings.cache_clear()
    with TestClient(app) as client:
        _mock_upstream_ok(client)
        payload = _payload()
        payload["request_id"] = "req-in-body"
        response = client.post("/v1/rerank", json=payload)
        assert response.status_code == 400
        assert "headers only" in response.json()["error"]

        # Ensure the request is rejected before upstream proxy call.
        post = client.app.state.gateway_context.client.post
        assert post.await_count == 0


def test_conversation_id_omitted_generates_and_merges_response():
    get_settings.cache_clear()
    with TestClient(app) as client:
        _mock_upstream_ok(client)
        response = client.post("/v1/rerank", json=_payload())
        assert response.status_code == 200
        post = client.app.state.gateway_context.client.post
        sent_json = post.call_args.kwargs["json"]
        assert "conversation_id" not in sent_json
        assert "is_new_conversation" not in sent_json
        hdr = post.call_args.kwargs["headers"]
        assert hdr["x-conversation-id"].startswith("conv_")
        assert hdr["x-is-new-conversation"] == "true"
        body = response.json()
        assert body["conversation_id"] == hdr["x-conversation-id"]
        assert body["is_new_conversation"] is True


def test_conversation_id_provided_stripped_upstream():
    get_settings.cache_clear()
    with TestClient(app) as client:
        _mock_upstream_ok(client)
        payload = _payload()
        payload["conversation_id"] = "thread-abc"
        payload["is_new_conversation"] = False
        response = client.post("/v1/rerank", json=payload)
        assert response.status_code == 200
        post = client.app.state.gateway_context.client.post
        sent_json = post.call_args.kwargs["json"]
        assert "conversation_id" not in sent_json
        assert "is_new_conversation" not in sent_json
        hdr = post.call_args.kwargs["headers"]
        assert hdr["x-conversation-id"] == "thread-abc"
        assert hdr["x-is-new-conversation"] == "false"
        body = response.json()
        assert body["conversation_id"] == "thread-abc"
        assert body["is_new_conversation"] is False


def test_conversation_id_blank_generates_new():
    get_settings.cache_clear()
    with TestClient(app) as client:
        _mock_upstream_ok(client)
        payload = _payload()
        payload["conversation_id"] = "   "
        response = client.post("/v1/rerank", json=payload)
        assert response.status_code == 200
        hdr = client.app.state.gateway_context.client.post.call_args.kwargs["headers"]
        assert hdr["x-conversation-id"].startswith("conv_")
        assert hdr["x-is-new-conversation"] == "true"
